### ISSUE TITLE
aop1 cannot intercept if base name in dottedPath is same as another bean

### ISSUE THREAD

**Issue by nicholaswguidry** [framework-one/fw1#518] opened 2020-03-17 23:53 UTC
It was discovered that attempting to intercept beanName="testDAO" would never trigger if "testService" also existed.
 For example if `model.services.test` and `model.daos.test` both exist, you can not have interceptors using beanName `testDAO`. Upon diving in to `aop.cfc` it was determined the reason is that aop using simply `test` as beanName in getAliases() is coming back with the targetBean of `testService`.

A simple application can be used to re-create the issue: [see here](https://github.com/nicholaswguidry/aop1-conflictingBeanName)

**Comment by sneiland** [comment] 2020-03-22 20:14
I've noticed similar behavior with DI/1. I'll need to dig into this to determine if the root cause is DI/1 or AOP1.

**Comment by lramirez925** [comment] 2021-09-13 18:42
Would it be useful to possibly separate out the bean factory/AOP code from the Framework repo? DI/1 and AOP1 both have a much smaller footprint and easier tests. Small improvements like this wouldn't require waiting for a full FW release.

**Comment by sneiland** [comment] 2021-10-29 20:58
I have to think on this a bit on what makes the most sense to set that up but it does seem to make sense.

**Comment by websolete** [comment] 2024-06-01 17:15
According to the changelog [here](https://framework-one.github.io/documentation/changelog/) this was addressed in the 4.3 release.

**Closed** 2024-06-26 17:11 UTC
Labels: needsanalysis
