### ISSUE TITLE
getFullyQualifiedAction() includes subsystem delimiter for default action

### ISSUE THREAD

**Issue by msp1kpj** [framework-one/fw1#379] opened 2015-09-30 17:03 UTC
Hello,

I wrote before about having an issue with the sub-system default action. I think that it is a bug. 
Setup:
Here is my framework config 
 variables.framework = {
        diEngine = 'app.framework.ioc'
        , diLocations = "/app/model/services,/app/model/gateways,./app/model/helpers"
        , base = '/app'
        , reloadApplicationOnEveryRequest = this.development
        , trace = this.development
        , generateSES = true
        , SESOmitIndex = true
        , cacheFileExists = !this.development
        , unhandledPaths = '/api'
    };

When I go to http://loalhost/ I expected the "rc.action" to be "main.default" but instead I get ":main.deafult". Since I have built my security model around the rc.action this change is breaking my security.

I am using the getSectionAndItem(":main.default") as a reference of what to expect and it is not the same as the default action.

**Comment by Richardtugwell** [comment] 2015-09-30 17:11
Are you using subsystems? getSectionAndItem should be subsystem agnostic as
far as I can tell from the docs. Why prepend ':' to main.default?

On 30 September 2015 at 18:03, Ken John <notifications@github.com> wrote:

> Hello,
>
> I wrote before about having an issue with the sub-system default action. I
> think that it is a bug.
> Setup:
> Here is my framework config
> variables.framework = {
> diEngine = 'app.framework.ioc'
> , diLocations =
> "/app/model/services,/app/model/gateways,./app/model/helpers"
> , base = '/app'
> , reloadApplicationOnEveryRequest = this.development
> , trace = this.development
> , generateSES = true
> , SESOmitIndex = true
> , cacheFileExists = !this.development
> , unhandledPaths = '/api'
> };
>
> When I go to http://loalhost/ I expected the "rc.action" to be
> "main.default" but instead I get ":main.deafult". Since I have built my
> security model around the rc.action this change is breaking my security.
>
> I am using the getSectionAndItem(":main.default") as a reference of what
> to expect and it is not the same as the default action.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/framework-one/fw1/issues/379>.
>



-- 
=================================
Richard Tugwell
http://blog.richardtugwell.com
r.tugwell@forthmedia.com

**Comment by seancorfield** [comment] 2015-09-30 17:12
Not a bug. `rc.action` is only mentioned in one place in the docs (as a way to see which action caused `onMissingView()` to be called) and if you look at http://framework-one.github.io/documentation/3.5/reference-manual.html#request-scope you'll see this comment about `request.action` (which is a legacy version of `rc.action`):

> `request.action` - The action specified in the URL or form (after expansion to the fully qualified form). This can be obtained by calling `getSubsystemSectionAndItem()`. Depending on the format you want, you may want to call `getFullyQualifiedAction()` instead, which will only contain the subsystem delimiter if the subsystem name is non-empty. That is the legacy format (for Subsystems 1.0 applications or applications containing no subsystems).

You should use the `get*` functions instead of accessing `rc.action` directly.

**Comment by seancorfield** [comment] 2015-09-30 17:16
Also note that `rc.action` only works if your `framework.action` config is set to `"action"` so it really should never be used directly in code (and that means that note in the `onMissingView()` section of the docs is wrong, really).

**Comment by msp1kpj** [comment] 2015-09-30 18:44
ok, I have updated my code to use getFullyQualifiedAction() and that still returns ":main.default" for http://localhost/ and "main.default" for http://localhost/main/default

**Comment by seancorfield** [comment] 2015-09-30 20:59
OK, that definitely should not happen -- and I've reproduced it locally: `getFullyQualifiedAction()` should never include the subsystem delimiter if there's no subsystem.

**Comment by seancorfield** [comment] 2015-09-30 22:23
This should be fixed in the latest *develop* download. I guess I'll be doing an RC 2 since folks have run into a number of bugs in RC 1... :)

**Closed by seancorfield** 2015-09-30 22:23 UTC
Labels: blocker
