### ISSUE TITLE
Preserve does not preserving data

### ISSUE THREAD

**Issue by tkiansoon** [framework-one/fw1#489] opened 2017-09-06 13:08 UTC
Has anyone experienced issue with preserve functionality in fw/1 version 4.1.0? I'm having issue with sessionLock(); is not returning the nextPreserveKey in getNextPreserveKeyAndPurgeOld(). 

If I replace the sessionLock() with lock scope="session" type="exclusive" timeout="30" then it solves the issue.

I'm running Lucee 4.5.5.006 final with sessionType=cfml and sessionStorage=file in my local development.

<code>
private string function getNextPreserveKeyAndPurgeOld() {

       var nextPreserveKey = '';
       var oldKeyToPurge = '';
        try {
            //sessionLock(function(){
            lock scope="session" type="exclusive" timeout="30" {
                if ( variables.framework.maxNumContextsPreserved > 1 ) {
                    sessionDefault( '__fw1NextPreserveKey', 1 );
                    nextPreserveKey = sessionRead( '__fw1NextPreserveKey' );
                    sessionWrite( '__fw1NextPreserveKey', nextPreserveKey + 1 );
                    oldKeyToPurge = nextPreserveKey - variables.framework.maxNumContextsPreserved;
                } else {
                    nextPreserveKey = '';
                    sessionWrite( '__fw1PreserveKey', nextPreserveKey );
                    oldKeyToPurge = '';
                }
            }
            //});
            var key = getPreserveKeySessionKey( oldKeyToPurge );
            if ( sessionHas( key ) ) {
                sessionDelete( key );
            }
        } catch ( any e ) {
            // ignore - assume session scope is disabled
        }
        return nextPreserveKey;
    }
</code>

**Comment by seancorfield** [comment] 2017-09-06 15:45
I just tested this on Lucee 4.5.5 and Lucee 5 and it works perfectly.

What do you have `maxNumContextsPreserved` set to in your `framework` configuration struct?

**Comment by tkiansoon** [comment] 2017-09-06 17:41
I didn't explicitly set the maxNumContextsPreserved in my framework configuration and I debug out the value is 10 (by fw/1 default).

**Comment by seancorfield** [comment] 2017-09-06 18:17
Since I cannot reproduce and everyone relies on this feature and no one else has reported it broken, I'm going to assert "not a bug" and close this -- and ask that you bring it up on the mailing list so folks can help you debug this and isolate what is causing the behavior you are seeing.

**Closed by seancorfield** 2017-09-06 18:17 UTC
